server:
    port: 8081

spring:
    application:
        name: USUARIO

eureka:
    client:
        service-url:
            defaultZone:http://localhost:8761/eureka/

spring:
    cloud:
        config:
            uri: http://localhost:8888


spring:
    datasoure:
        url:
        driver-class-name: org.h2.Driver
        username:
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

